name: CI Pipeline
on:
  push:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn clean test

  build:
    runs-on: ubuntu-latest
    needs: test
    name: Build Docker Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t mailing-system:${{ github.sha }} .

  # Job that will fail the entire workflow if tests or build fail
  validate-deployment:
    runs-on: ubuntu-latest
    needs: [test, build]
    name: Validate Deployment

    steps:
      - name: Deployment validation
        run: |
          echo "✅ All tests passed"
          echo "✅ Build successful" 
          echo "✅ Ready for deployment"